fix target permissions

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -75,7 +75,7 @@ jobs:
       - name: Deploy with rsync into /tmp
         shell: bash
         run: |
-          rsync -avz --owner=${{ secrets.SSH_USERNAME }} --group=${{ secrets.SSH_USERNAME }} -e 'ssh -p ${{ secrets.SSH_PORT }}' ./$ADDON_NAME/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/tmp/$ADDON_NAME.$UUID
+          rsync -avz -e 'ssh -p ${{ secrets.SSH_PORT }}' ./$ADDON_NAME/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/tmp/$ADDON_NAME.$UUID
 
       - name: (Dry Run) Copy to Odoo Addons Directory
         uses: appleboy/ssh-action@v1.0.3
@@ -91,5 +91,14 @@ jobs:
           envs: ODOO1_ADDONS_DIR,ADDON_NAME,UUID
           script: |
             ADDON_DIR=$ODOO1_ADDONS_DIR/$ADDON_NAME
+            TMP_ADDON_DIR=/tmp/$ADDON_NAME.$UUID
+
+            if [[ "$ADDON_DIR" == "/" ]] || [[ "$ADDON_DIR" == *"/.."* ]]; then
+                echo "Invalid path: $ADDON_DIR. Path must not be the root directory or traverse upwards."
+                exit 1
+            fi
+
+            chown -R ${{ secrets.SSH_USERNAME }}:${{ secrets.SSH_USERNAME }} $TMP_ADDON_DIR
+
             echo "mkdir -p $ADDON_DIR"
-            echo "cp -r /tmp/$ADDON_NAME.$UUID/* $ADDON_DIR/"
+            echo "cp -r $TMP_ADDON_DIR/* $ADDON_DIR/"
